"""Client (tenant) plane — self-service reports & exports.

Clients generate, preview and download the SAME payroll outputs operators do —
the payroll workbook, the bank transfer listing, and the GRA Employer's Monthly
Tax Deductions (P.A.Y.E.) schedule — for their OWN runs, without operator
intervention. This is a thin wrapper over the shared export engine in
``app/excel_utils.py``: no business logic is reproduced here, so a client export
is byte-for-byte the operator export.

Tenancy: every run is fetched via ``tenant_get_or_404`` so a client can only ever
export their own company's run (another tenant's id is a 404). Lifecycle: reports
are the final outputs of a finalized run, so they unlock only once the run is
completed (``CLOSED_STATUSES`` = Approved/Processed), mirroring the client
distribution gate. Unlike the operator payroll export, a client export never
advances the run to Processed — closing a run stays an operator/accounts action.

Identity: a client is the employer of their own workers, so their exports carry
THEIR company name (the letterhead / GRA Name of Employer), never the platform
bureau's — and their GRA schedule is never stamped with the bureau's TIN or tax
office. The calculation engine and template are otherwise identical to the
operator export.
"""
from flask import (
    current_app,
    flash,
    redirect,
    render_template,
    send_file,
    url_for,
)

from app import db
from app.audit import record_audit
from app.client import _company, client_bp
from app.excel_utils import (
    bank_listing_groups,
    export_bank_listing,
    export_gra_paye_schedule,
    export_payroll_run,
)
from app.models import PayrollRun
from app.payroll_status import CLOSED_STATUSES
from app.tenancy import tenant_get_or_404, tenant_required


def _guard_completed(run):
    """A report is only meaningful for a finalized run. Returns a redirect
    response when the run isn't completed yet (Approved/Processed), else None."""
    if run.status not in CLOSED_STATUSES:
        flash("Reports unlock once the payroll run is approved.", "warning")
        return redirect(url_for("client.run_reports", run_id=run.id))
    return None


def _employer_name(run):
    """The employer/company shown on a client's own exports: their OWN company,
    not the platform bureau. A client is the employer of their workers, so their
    exports (payroll workbook, bank listing, GRA PAYE schedule) carry their name.
    Falls back to the active tenant if the run's relationship is unset."""
    if run.client_company:
        return run.client_company.name
    company = _company()
    return company.name if company else "Client"


@client_bp.route("/runs/<int:run_id>/reports")
@tenant_required
def run_reports(run_id):
    """Preview hub: the run's headline figures, a per-bank breakdown (the bank
    listing preview) and PAYE totals, with a download for each export."""
    run = tenant_get_or_404(PayrollRun, run_id)  # 404 if another tenant's run
    bank_groups, bank_grand_total = bank_listing_groups(run)
    return render_template(
        "client/run_reports.html",
        company=_company(),
        run=run,
        completed=run.status in CLOSED_STATUSES,
        bank_groups=bank_groups,
        bank_grand_total=bank_grand_total,
        employer_name=_employer_name(run),
    )


@client_bp.route("/runs/<int:run_id>/export")
@tenant_required
def download_payroll(run_id):
    """Full payroll workbook for the run (all items + totals). Unlike the operator
    export it does NOT mark the run Processed — a client export is read-only."""
    run = tenant_get_or_404(PayrollRun, run_id)
    guard = _guard_completed(run)
    if guard:
        return guard
    file_path = export_payroll_run(
        run, current_app.config["EXPORT_FOLDER"], org_name=_employer_name(run)
    )
    record_audit("Client payroll export", run, "Payroll workbook exported by client.")
    db.session.commit()
    return send_file(file_path, as_attachment=True)


@client_bp.route("/runs/<int:run_id>/export/bank-listing")
@tenant_required
def download_bank_listing(run_id):
    """Bank transfer batch listing grouped by bank (same engine as operators)."""
    run = tenant_get_or_404(PayrollRun, run_id)
    guard = _guard_completed(run)
    if guard:
        return guard
    file_path = export_bank_listing(
        run, current_app.config["EXPORT_FOLDER"], org_name=_employer_name(run)
    )
    record_audit("Client bank listing export", run, "Bank transfer listing generated by client.")
    db.session.commit()
    return send_file(file_path, as_attachment=True)


@client_bp.route("/runs/<int:run_id>/export/gra-paye")
@tenant_required
def download_gra_paye(run_id):
    """GRA Employer's Monthly Tax Deductions Schedule (P.A.Y.E.) — identical
    calculation engine, template and employer-of-record config as operators."""
    run = tenant_get_or_404(PayrollRun, run_id)
    guard = _guard_completed(run)
    if guard:
        return guard
    # A client is the employer on their own GRA filing, so it carries THEIR
    # company name — not the bureau's — and we never stamp the bureau's TIN or
    # tax office onto it (left blank for the client to hand-fill their own).
    file_path = export_gra_paye_schedule(
        run,
        current_app.config["EXPORT_FOLDER"],
        employer_name=_employer_name(run),
    )
    record_audit("Client GRA PAYE export", run, "GRA PAYE schedule generated by client.")
    db.session.commit()
    return send_file(file_path, as_attachment=True)
