"""The migration chain must be able to build the database it describes.

For a year it could not. The chain began at ``d450b1a3317e``, which creates no
tables — it only adds foreign keys, having been autogenerated against a database
``db.create_all()`` had already built. So ``flask db upgrade`` against an empty
database died on the first revision with ``NoSuchTableError: expense``. Every
environment got its schema from ``create_all()`` and layered migrations on top;
none was ever built from the chain alone, so nothing noticed.

That is a disaster-recovery gap (the migrations cannot rebuild production from
source) and a hard blocker for any packaged install, whose first run has nothing
to layer onto. ``f0e1d2c3b4a5`` is the reconstructed root that closes it.

The test below is the oracle that proves the reconstruction is right. There is
no way to reach the correct end state from the wrong starting schema through 33
unmodified revisions, so if a chain-built database matches a models-built one
table for table and column for column, the root is correct. It is also the
regression guard: the next migration that assumes a pre-existing table, or that
drifts from the model it mirrors, fails here rather than in a recovery.
"""
import os
import tempfile
import unittest

os.environ["SKIP_DOTENV"] = "true"
os.environ["DATABASE_URL"] = "sqlite:///:memory:"
os.environ["PERSISTENCE_REQUIRED"] = "false"

from sqlalchemy import create_engine, inspect  # noqa: E402

from app import create_app, db  # noqa: E402


def describe(engine):
    """Everything about a schema that the two build routes must agree on."""
    inspector = inspect(engine)
    schema = {}
    for table in inspector.get_table_names():
        if table == "alembic_version":  # bookkeeping, absent from create_all
            continue
        columns = inspector.get_columns(table)
        schema[table] = {
            "columns": {c["name"]: str(c["type"]).upper() for c in columns},
            "nullable": sorted(c["name"] for c in columns if c["nullable"]),
            "pk": sorted(inspector.get_pk_constraint(table).get("constrained_columns") or []),
            "fks": sorted(
                (tuple(f["constrained_columns"]), f["referred_table"],
                 tuple(f["referred_columns"]))
                for f in inspector.get_foreign_keys(table)
            ),
            # Compared by shape, not name: an index's name is cosmetic, the
            # columns it covers and whether it is unique are not.
            "indexes": sorted(
                (tuple(i["column_names"]), bool(i["unique"]))
                for i in inspector.get_indexes(table)
            ),
        }
    return schema


class MigrationChainBuildsTheSchemaTests(unittest.TestCase):
    """`flask db upgrade` from empty must equal `db.create_all()`."""

    @classmethod
    def setUpClass(cls):
        from flask_migrate import upgrade

        cls._saved = {
            key: os.environ.get(key)
            for key in ("PAYROLLA_INSTANCE_PATH", "AUTO_INIT_DB", "DATABASE_URL")
        }
        cls._tmp = tempfile.TemporaryDirectory()

        # Route 1: the chain, from nothing, against a real file-backed SQLite
        # database. In-memory would not do — each connection gets its own blank
        # database, so the migrations would have nothing to build on.
        os.environ.pop("DATABASE_URL", None)
        os.environ["AUTO_INIT_DB"] = "false"
        os.environ["PAYROLLA_INSTANCE_PATH"] = cls._tmp.name
        app = create_app()
        with app.app_context():
            upgrade()
            cls.migrated = describe(db.engine)

        # Route 2: the models, straight to a second file. No second app needed —
        # the metadata is already loaded and can build itself anywhere.
        models_db = os.path.join(cls._tmp.name, "from_models.db")
        engine = create_engine(f"sqlite:///{models_db}")
        db.metadata.create_all(engine)
        cls.from_models = describe(engine)
        engine.dispose()

    @classmethod
    def tearDownClass(cls):
        for key, value in cls._saved.items():
            if value is None:
                os.environ.pop(key, None)
            else:
                os.environ[key] = value
        try:
            cls._tmp.cleanup()
        except (OSError, PermissionError):
            # Windows keeps a handle on the SQLite file briefly after dispose;
            # a leaked temp dir must not fail an otherwise passing suite.
            pass

    def test_the_chain_runs_from_empty_at_all(self):
        """The original failure: this died on revision one with NoSuchTableError."""
        self.assertTrue(self.migrated, "the migration chain produced no tables")

    def test_the_same_tables_exist(self):
        self.assertEqual(sorted(self.migrated), sorted(self.from_models))

    def test_every_table_has_the_same_columns_and_types(self):
        for table in sorted(self.migrated):
            with self.subTest(table=table):
                self.assertEqual(
                    self.migrated[table]["columns"],
                    self.from_models[table]["columns"],
                )

    def test_nullability_matches(self):
        """Caught a real drift: the chain left a NOT NULL column nullable."""
        for table in sorted(self.migrated):
            with self.subTest(table=table):
                self.assertEqual(
                    self.migrated[table]["nullable"],
                    self.from_models[table]["nullable"],
                )

    def test_keys_and_indexes_match(self):
        for table in sorted(self.migrated):
            for aspect in ("pk", "fks", "indexes"):
                with self.subTest(table=table, aspect=aspect):
                    self.assertEqual(
                        self.migrated[table][aspect],
                        self.from_models[table][aspect],
                    )

    def test_the_archived_ops_tables_do_not_survive(self):
        """The root creates 14 legacy tables purely so f969702561b6 can drop them.

        If a refactor ever 'tidies' them out of the root, the drop revision will
        fail; if the drop is removed, they leak into every new database. Either
        way this is the check that notices.
        """
        for table in ("invoice", "product", "supplier", "cleaning_job",
                      "attendance_record", "worker_assignment"):
            with self.subTest(table=table):
                self.assertNotIn(table, self.migrated)


if __name__ == "__main__":
    unittest.main()
