"""Phase 2, Task 2.6 — development data at a scale that exposes density defects.

The demo fixture in :mod:`app.seed` is deliberately two companies and twenty
employees: enough to demonstrate the product, and small enough that every
pagination, N+1 and information-density problem stays invisible. Phases 3–7 fix
exactly those problems, so they cannot be validated against it.

This is **additive and opt-in**. It never touches the demo fixture — roughly six
hundred tests pin those exact companies, users and staff IDs — and it is not
wired into ``SEED_DEMO_DATA``. Run it deliberately:

    flask --app run:app seed-scale
    flask --app run:app seed-scale --clients 60 --large-run 800
    flask --app run:app seed-scale --undo

Everything it creates is prefixed/suffixed so it is identifiable and removable:
company codes ``SC###``, staff IDs ``SC-…``, contact domain ``scale.test``. It is
idempotent — a second run adds nothing.

It is safe against the wrong database: it refuses to run unless the target looks
like a development database, because generating 20k rows into the production
Supabase instance would be very hard to unpick.
"""
import random
from datetime import datetime, timedelta

import click
from flask import current_app

from app import db
from app.models import ClientCompany, Employee, PayrollItem, PayrollRun, User
from app.payroll_status import (
    APPROVED,
    DRAFT,
    HELD,
    PENDING_APPROVAL,
    PROCESSED,
    REJECTED,
)

# Markers that make everything this module creates identifiable, so --undo can
# remove precisely it and nothing else.
CODE_PREFIX = "SC"
STAFF_PREFIX = "SC-"
EMAIL_DOMAIN = "scale.test"

_FIRST = [
    "Kwame", "Akosua", "Yaw", "Ama", "Kofi", "Efua", "Kojo", "Abena", "Nana",
    "Esi", "Akua", "Afia", "Kwabena", "Adwoa", "Kwesi", "Yaa", "Fiifi", "Maame",
]
_LAST = [
    "Mensah", "Osei", "Boateng", "Serwaa", "Appiah", "Nyarko", "Antwi", "Darko",
    "Adu", "Amponsah", "Addai", "Tetteh", "Nartey", "Asamoah", "Owusu", "Baidoo",
]
_SECTORS = [
    "Port operations support", "Manufacturing & warehouse", "Facilities management",
    "Security services", "Logistics & haulage", "Catering & hospitality",
    "Retail operations", "Agro-processing", "Construction support",
]
_TOWNS = ["Tema", "Accra", "Takoradi", "Kumasi", "Cape Coast", "Tamale", "Ho", "Sunyani"]

# Statuses spread across generated runs so every lifecycle branch — and every
# recommended_action_for() answer — has real data behind it on a list page.
_STATUS_CYCLE = [
    DRAFT, PENDING_APPROVAL, APPROVED, PROCESSED, HELD, REJECTED, APPROVED, DRAFT,
]
_MONTHS = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
]


def _looks_like_production():
    """True when the configured database is not obviously a dev one."""
    uri = (current_app.config.get("SQLALCHEMY_DATABASE_URI") or "").lower()
    if "sqlite" in uri or "localhost" in uri or "127.0.0.1" in uri:
        return False
    return True


def _make_company(index, rng):
    code = f"{CODE_PREFIX}{index:03d}"
    town = rng.choice(_TOWNS)
    return ClientCompany(
        name=f"{rng.choice(_LAST)} {rng.choice(['Holdings', 'Industries', 'Services', 'Group', 'Logistics'])} {code}",
        company_code=code,
        contact_person=f"{rng.choice(_FIRST)} {rng.choice(_LAST)}",
        email=f"contact-{code.lower()}@{EMAIL_DOMAIN}",
        phone=f"0302{rng.randint(100000, 999999)}",
        address=f"{rng.randint(1, 120)} {town} Industrial Road",
        location=town,
        service_type=rng.choice(_SECTORS),
        status="Active",
        notes="Generated by seed-scale (development data).",
    )


def _make_employee(company, seq, rng):
    staff_id = f"{STAFF_PREFIX}{company.company_code}-{seq:04d}"
    return Employee(
        staff_id=staff_id,
        full_name=f"{rng.choice(_FIRST)} {rng.choice(_LAST)}",
        phone=f"024{rng.randint(1000000, 9999999)}",
        ghana_card_number=f"GHA-{rng.randint(10000000, 99999999)}-{seq % 10}",
        ssnit_number=f"SSNIT-{rng.randint(100000, 999999)}",
        bank_name=rng.choice(["GCB Bank", "Ecobank", "Fidelity Bank", "Absa", "Stanbic"]),
        bank_account_number=f"{rng.randint(1000000000, 9999999999)}",
        momo_number=f"055{rng.randint(1000000, 9999999)}",
        employment_type="Outsourced Staff",
        service_line=company.service_type,
        assigned_client=company.name,
        client_company_id=company.id,
        status="Active" if seq % 17 else "Inactive",
        basic_salary=rng.randrange(1800, 6500, 50),
    )


def _add_items(run, employees, rng):
    """Cost a run's employees and roll the totals up onto it."""
    gross_t = ded_t = net_t = paye_t = ssnit_t = 0.0
    for employee in employees:
        basic = employee.basic_salary or 2000
        transport, housing = 250, 300
        overtime = rng.choice([0, 0, 80, 140, 220])
        gross = basic + transport + housing + overtime
        paye = round(gross * 0.08, 2)
        ssnit = round(gross * 0.055, 2)
        deductions = paye + ssnit
        net = gross - deductions
        db.session.add(PayrollItem(
            payroll_run_id=run.id,
            employee_id=employee.id,
            staff_id=employee.staff_id,
            full_name=employee.full_name,
            ssnit_number=employee.ssnit_number,
            basic_salary=basic,
            transport_allowance=transport,
            housing_allowance=housing,
            overtime_pay=overtime,
            other_allowances=0,
            gross_pay=gross,
            paye=paye,
            ssnit=ssnit,
            other_deductions=0,
            total_deductions=deductions,
            net_pay=net,
            validation_status="OK",
        ))
        gross_t += gross
        ded_t += deductions
        net_t += net
        paye_t += paye
        ssnit_t += ssnit
    run.total_workers = len(employees)
    run.total_rows_imported = len(employees)
    run.total_gross_pay = gross_t
    run.total_deductions = ded_t
    run.total_net_pay = net_t
    run.total_paye = paye_t
    run.total_ssnit = ssnit_t


def seed_scale(clients=40, employees_per_client=12, large_run=400, runs_per_client=3, seed=20260731):
    """Generate the development corpus. Returns a summary dict."""
    rng = random.Random(seed)
    if ClientCompany.query.filter(
        ClientCompany.company_code.like(f"{CODE_PREFIX}%")
    ).count():
        return {"created": False, "reason": "already seeded"}

    admin = User.query.filter_by(email="admin@payrolla.com").first()
    director = User.query.filter_by(email="director@payrolla.com").first()
    if admin is None:
        return {"created": False, "reason": "run the demo seed first (no admin user)"}

    now = datetime.now()
    companies, made_runs, made_employees = [], 0, 0

    for index in range(1, clients + 1):
        company = _make_company(index, rng)
        db.session.add(company)
        companies.append(company)
    db.session.flush()

    for position, company in enumerate(companies):
        # One company carries a deliberately large roster, so a single run is big
        # enough to expose per-row page cost (Task 4.1 is measured against it).
        count = large_run if position == 0 else employees_per_client
        roster = [_make_employee(company, seq, rng) for seq in range(1, count + 1)]
        db.session.add_all(roster)
        made_employees += len(roster)
        db.session.flush()

        payable = [e for e in roster if e.status == "Active"]
        for back in range(runs_per_client):
            when = now - timedelta(days=30 * back)
            status = _STATUS_CYCLE[(position + back) % len(_STATUS_CYCLE)]
            run = PayrollRun(
                month=_MONTHS[when.month - 1],
                year=when.year,
                status=status,
                created_by=admin.id,
                approved_by=director.id if status in (APPROVED, PROCESSED) and director else None,
                client_company_id=company.id,
                duplicate_workers_found=0,
                source_filename=f"{company.company_code.lower()}_{when.strftime('%Y_%m')}.xlsx",
                import_type="Single Company Upload",
                notes="Generated by seed-scale (development data).",
                created_at=when,
            )
            db.session.add(run)
            db.session.flush()
            # A Draft run that has not been calculated yet is a real state the
            # recommended-action logic must handle, so leave some uncosted.
            if status == DRAFT and back == 0:
                run.total_workers = len(payable)
                run.total_rows_imported = len(payable)
            else:
                _add_items(run, payable, rng)
            made_runs += 1
        db.session.commit()

    return {
        "created": True,
        "clients": len(companies),
        "employees": made_employees,
        "runs": made_runs,
        "largest_run": large_run,
    }


def undo_scale():
    """Remove everything seed_scale created, and nothing else."""
    companies = ClientCompany.query.filter(
        ClientCompany.company_code.like(f"{CODE_PREFIX}%")
    ).all()
    ids = [c.id for c in companies]
    if not ids:
        return {"removed": 0}
    runs = PayrollRun.query.filter(PayrollRun.client_company_id.in_(ids)).all()
    run_ids = [r.id for r in runs]
    if run_ids:
        PayrollItem.query.filter(PayrollItem.payroll_run_id.in_(run_ids)).delete(
            synchronize_session=False
        )
        PayrollRun.query.filter(PayrollRun.id.in_(run_ids)).delete(
            synchronize_session=False
        )
    Employee.query.filter(Employee.client_company_id.in_(ids)).delete(
        synchronize_session=False
    )
    ClientCompany.query.filter(ClientCompany.id.in_(ids)).delete(
        synchronize_session=False
    )
    db.session.commit()
    return {"removed": len(ids)}


def register_cli(app):
    @app.cli.command("seed-scale")
    @click.option("--clients", default=40, show_default=True, help="How many client companies.")
    @click.option("--employees", default=12, show_default=True, help="Roster size per client.")
    @click.option("--large-run", default=400, show_default=True,
                  help="Roster size for the one deliberately large client.")
    @click.option("--runs", default=3, show_default=True, help="Payroll runs per client.")
    @click.option("--undo", is_flag=True, help="Remove everything seed-scale created.")
    @click.option("--force", is_flag=True, help="Allow running against a non-development database.")
    def seed_scale_command(clients, employees, large_run, runs, undo, force):
        """Generate development data dense enough to expose density defects."""
        if _looks_like_production() and not force:
            raise click.ClickException(
                "DATABASE_URL does not look like a development database. This "
                "generates tens of thousands of rows — point it at a local DB, or "
                "pass --force if you are certain."
            )
        if undo:
            click.echo(f"Removed {undo_scale()['removed']} generated client(s).")
            return
        result = seed_scale(
            clients=clients,
            employees_per_client=employees,
            large_run=large_run,
            runs_per_client=runs,
        )
        if not result["created"]:
            raise click.ClickException(result["reason"])
        click.echo(
            f"Seeded {result['clients']} clients, {result['employees']} employees, "
            f"{result['runs']} runs (largest roster: {result['largest_run']})."
        )
