"""Object storage behind one swappable seam.

Files the app must keep (today: expense receipts) are addressed by an opaque
**storage key** — a POSIX-style relative path like
``receipts/12/3f2a…-receipt.pdf`` — never by a filesystem path. Callers hand a
key to a backend and get bytes back; where those bytes actually live is the
backend's business.

That indirection is the point. ``LocalStorageBackend`` writes under a configured
root directory, which is all a single-node deployment needs. Moving to Supabase
Storage means implementing :class:`StorageBackend` once against the same four
methods and flipping ``STORAGE_BACKEND`` — the keys already recorded in the
database stay valid, because a key was never a path. No route, model, template
or test changes.

Nothing in this module knows what a receipt is. Domain rules — which MIME types
are allowed, how big a file may be, which tenant a key belongs to — live in
:mod:`app.receipts`. Keeping storage domain-agnostic is what makes it reusable
for the next thing that needs a file (payslip archives, onboarding documents).

**Path traversal.** Keys are validated by :func:`safe_key` before any backend
touches them, and :class:`LocalStorageBackend` additionally re-checks that the
resolved absolute path is inside its root. Two independent gates, because a key
can reach this module from a URL.
"""

import os
import re
import shutil

from flask import current_app

# A key is lowercase-ish path segments joined by "/". No leading slash, no "..",
# no backslashes, no drive letters, no empty segments. Deliberately strict: keys
# are generated by this app (uuid + sanitised extension), never typed by a user,
# so anything outside this shape is an attack or a bug.
_KEY_SEGMENT = r"[A-Za-z0-9][A-Za-z0-9._-]*"
_KEY_RE = re.compile(rf"^{_KEY_SEGMENT}(?:/{_KEY_SEGMENT})*$")

# Segments that are legal by the pattern above but must never appear.
_FORBIDDEN_SEGMENTS = {os.curdir, os.pardir}


class StorageError(Exception):
    """A storage operation failed (bad key, missing object, unwritable root)."""


def safe_key(key):
    """Return ``key`` if it is a legal storage key, else raise :class:`StorageError`.

    Rejects absolute paths, ``..`` traversal, backslashes, NUL bytes, empty
    segments and anything with characters outside the allowed set. Call this
    before handing a key to any backend — every backend method already does, so
    a hostile key fails identically whichever backend is configured.
    """
    if not isinstance(key, str):
        raise StorageError("Storage key must be a string.")
    candidate = key.strip()
    if not candidate:
        raise StorageError("Storage key must not be empty.")
    if "\x00" in candidate or "\\" in candidate:
        raise StorageError("Storage key contains an illegal character.")
    if not _KEY_RE.match(candidate):
        raise StorageError(f"Illegal storage key: {key!r}")
    if any(part in _FORBIDDEN_SEGMENTS for part in candidate.split("/")):
        raise StorageError(f"Illegal storage key: {key!r}")
    return candidate


class StorageBackend:
    """The contract every backend implements.

    Four operations, all keyed by a storage key: ``save``, ``open``, ``delete``,
    ``exists``. A backend may also offer :meth:`url` for a direct/signed link;
    returning ``None`` (the default) means "no direct URL — stream it through the
    app", which is what the local backend does and what keeps the tenant
    authorization check on the download route meaningful.
    """

    name = "abstract"

    def save(self, key, stream, content_type=None):
        """Persist ``stream`` (a file-like open in binary mode) at ``key``.

        Returns the number of bytes written. Overwrites an existing object at
        the same key — keys are uuid-based, so in practice this never collides.
        """
        raise NotImplementedError

    def open(self, key):
        """Return a binary file-like for ``key``. Raises :class:`StorageError` if absent."""
        raise NotImplementedError

    def delete(self, key):
        """Remove ``key``. Returns True if something was removed, False if it was
        already gone. Never raises for a missing object — delete is idempotent so
        that cleaning up after a half-failed upload can't itself fail."""
        raise NotImplementedError

    def exists(self, key):
        raise NotImplementedError

    def url(self, key):  # pragma: no cover - overridden by remote backends
        """A directly fetchable URL for ``key``, or None if the app must stream it."""
        return None


class LocalStorageBackend(StorageBackend):
    """Filesystem-backed storage rooted at a single directory.

    The default for local development and single-node deployments. Note the root
    is *outside* the application package (``instance/`` by default), so stored
    files are never importable, never served statically, and never picked up by
    a template loader — they can only leave through the download route, which
    checks tenant ownership first.
    """

    name = "local"

    def __init__(self, root):
        self.root = os.path.abspath(root)

    def _path(self, key):
        """Absolute path for ``key``, proven to be inside :attr:`root`.

        ``safe_key`` has already rejected traversal, but this re-checks the
        *resolved* path. That second gate catches what pattern-matching cannot:
        a symlink inside the root pointing out of it.
        """
        relative = safe_key(key)
        path = os.path.abspath(os.path.join(self.root, relative))
        root = self.root + os.sep
        if not path.startswith(root):
            raise StorageError(f"Storage key escapes the storage root: {key!r}")
        return path

    def save(self, key, stream, content_type=None):
        path = self._path(key)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "wb") as handle:
            shutil.copyfileobj(stream, handle)
        return os.path.getsize(path)

    def open(self, key):
        path = self._path(key)
        try:
            return open(path, "rb")
        except OSError as exc:
            raise StorageError(f"Stored object is missing: {key!r}") from exc

    def delete(self, key):
        path = self._path(key)
        try:
            os.remove(path)
            return True
        except FileNotFoundError:
            return False
        except OSError as exc:
            raise StorageError(f"Could not delete stored object: {key!r}") from exc

    def exists(self, key):
        return os.path.isfile(self._path(key))


def _build_backend(app):
    name = (app.config.get("STORAGE_BACKEND") or "local").strip().lower()
    if name == "local":
        return LocalStorageBackend(app.config["STORAGE_ROOT"])
    # Supabase Storage is the planned next backend: implement StorageBackend
    # against supabase.storage.from_(bucket) and register it here. Nothing else
    # in the app changes — stored keys are already backend-neutral.
    raise StorageError(
        f"Unknown STORAGE_BACKEND {name!r}. Supported backends: 'local'."
    )


def get_storage(app=None):
    """The configured backend for this app, built once and cached on it.

    Cached in ``app.extensions`` rather than a module global so parallel test
    apps (each with its own temp root) never share a backend.
    """
    app = app or current_app
    backend = app.extensions.get("payrolla_storage")
    if backend is None:
        backend = _build_backend(app)
        app.extensions["payrolla_storage"] = backend
    return backend
