"""add tax_relief_monthly to employee

Revision ID: 912a1bf13693
Revises: a2e069c9765d
Create Date: 2026-07-02 18:13:43.277216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '912a1bf13693'
down_revision = 'a2e069c9765d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_relief_monthly', sa.Float(), nullable=True))

    with op.batch_alter_table('wage_rate_profiles', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)


    op.execute("UPDATE employee SET tax_relief_monthly = 0 WHERE tax_relief_monthly IS NULL")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wage_rate_profiles', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('tax_relief_monthly')

    # ### end Alembic commands ###
