"""add medical_allowance, productivity_bonus, pf_fund_employee to payroll_item

Revision ID: a1708da6fa0f
Revises: ec50a1d9972b
Create Date: 2026-07-02 13:25:20.370001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1708da6fa0f'
down_revision = 'ec50a1d9972b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medical_allowance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('productivity_bonus', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pf_fund_employee', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_item', schema=None) as batch_op:
        batch_op.drop_column('pf_fund_employee')
        batch_op.drop_column('productivity_bonus')
        batch_op.drop_column('medical_allowance')

    # ### end Alembic commands ###
