"""add category to wage_rate_profiles

Revision ID: a2e069c9765d
Revises: c802396b35b8
Create Date: 2026-07-02 14:11:48.415073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2e069c9765d'
down_revision = 'c802396b35b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statutory_rates', schema=None) as batch_op:
        batch_op.alter_column('overtime_rate_low',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('overtime_rate_high',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('overtime_basic_threshold',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('bonus_rate',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('bonus_annual_basic_threshold',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('wage_rate_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=20), nullable=True))


    # Existing rates were all created before categorisation; 'basic' matches
    # the normal-hours codes they were entered for. Reclassify OT/bonus/
    # allowance codes in the Wage Rates screen before the next calculation.
    op.execute("UPDATE wage_rate_profiles SET category = 'basic' WHERE category IS NULL")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wage_rate_profiles', schema=None) as batch_op:
        batch_op.drop_column('category')

    with op.batch_alter_table('statutory_rates', schema=None) as batch_op:
        batch_op.alter_column('bonus_annual_basic_threshold',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('bonus_rate',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('overtime_basic_threshold',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('overtime_rate_high',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('overtime_rate_low',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
