"""add concessionary overtime and bonus rates to statutory_rates

Revision ID: c802396b35b8
Revises: a1708da6fa0f
Create Date: 2026-07-02 13:57:32.746887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c802396b35b8'
down_revision = 'a1708da6fa0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statutory_rates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overtime_rate_low', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('overtime_rate_high', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('overtime_basic_threshold', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bonus_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bonus_annual_basic_threshold', sa.Float(), nullable=True))


    # Backfill existing rate versions with the concessionary values encoded
    # in the ACS workbook's live formulas (verify against the GRA circular).
    op.execute(
        "UPDATE statutory_rates SET overtime_rate_low = 0.05, "
        "overtime_rate_high = 0.10, overtime_basic_threshold = 0.50, "
        "bonus_rate = 0.05, bonus_annual_basic_threshold = 0.15"
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statutory_rates', schema=None) as batch_op:
        batch_op.drop_column('bonus_annual_basic_threshold')
        batch_op.drop_column('bonus_rate')
        batch_op.drop_column('overtime_basic_threshold')
        batch_op.drop_column('overtime_rate_high')
        batch_op.drop_column('overtime_rate_low')

    # ### end Alembic commands ###
