"""initial baseline

Revision ID: d450b1a3317e
Revises: 
Create Date: 2026-07-01 16:35:40.956699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd450b1a3317e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'client_company', ['client_company_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['paid_by'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['approved_by'], ['id'])
        batch_op.create_foreign_key(None, 'payroll_run', ['payroll_run_id'], ['id'])

    with op.batch_alter_table('payment_voucher', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['reviewed_by'], ['id'])

    with op.batch_alter_table('payroll_run', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['reviewed_by'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'client_company', ['client_company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('payroll_run', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('payment_voucher', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
