"""initial baseline

Adds the foreign keys the live database was missing. It creates no tables: it
was autogenerated against a database db.create_all() had already built, so the
only difference it saw was the absent constraints. It is no longer the root —
f0e1d2c3b4a5 now creates the schema this revision assumes, so the chain can
build a database from empty. See that revision for the full account.

Revision ID: d450b1a3317e
Revises: f0e1d2c3b4a5
Create Date: 2026-07-01 16:35:40.956699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd450b1a3317e'
down_revision = 'f0e1d2c3b4a5'
branch_labels = None
depends_on = None


# Autogenerate emitted these seven constraints unnamed (``None``). On
# PostgreSQL that is survivable — batch_alter_table falls through to a plain
# ALTER and the server invents a name — which is why this revision has run in
# production for a year. On SQLite there is no ALTER for a constraint, so batch
# mode rebuilds the table and refuses an anonymous one outright:
# "ValueError: Constraint must have a name". Naming them is what lets the chain
# run on SQLite at all, and costs an already-migrated database nothing, because
# a revision that has run is never re-run.
#
# One consequence worth stating: a database rebuilt from this chain now carries
# these explicit names, while the live PostgreSQL instance still has the names
# the server generated in 2026. The constraints are identical in every other
# respect; only the labels differ.
_FOREIGN_KEYS = (
    # (table, constraint name, referred table, local columns, remote columns)
    ('expense', 'fk_expense_client_company_id', 'client_company', ['client_company_id'], ['id']),
    ('expense', 'fk_expense_paid_by', 'user', ['paid_by'], ['id']),
    ('expense', 'fk_expense_approved_by', 'user', ['approved_by'], ['id']),
    ('expense', 'fk_expense_payroll_run_id', 'payroll_run', ['payroll_run_id'], ['id']),
    ('payment_voucher', 'fk_payment_voucher_reviewed_by', 'user', ['reviewed_by'], ['id']),
    ('payroll_run', 'fk_payroll_run_reviewed_by', 'user', ['reviewed_by'], ['id']),
    ('user', 'fk_user_client_company_id', 'client_company', ['client_company_id'], ['id']),
)


def upgrade():
    for table in ('expense', 'payment_voucher', 'payroll_run', 'user'):
        with op.batch_alter_table(table, schema=None) as batch_op:
            for owner, name, referred, local, remote in _FOREIGN_KEYS:
                if owner == table:
                    batch_op.create_foreign_key(name, referred, local, remote)


def downgrade():
    for table in ('user', 'payroll_run', 'payment_voucher', 'expense'):
        with op.batch_alter_table(table, schema=None) as batch_op:
            for owner, name, _referred, _local, _remote in _FOREIGN_KEYS:
                if owner == table:
                    batch_op.drop_constraint(name, type_='foreignkey')
