"""add statutory_rates and wage_rate_profiles tables

Revision ID: ec50a1d9972b
Revises: f969702561b6
Create Date: 2026-07-02 10:16:12.552730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec50a1d9972b'
down_revision = 'f969702561b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statutory_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('ssf_employee_rate', sa.Float(), nullable=False),
    sa.Column('ssf_employer_rate', sa.Float(), nullable=False),
    sa.Column('paye_bands_json', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('statutory_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_statutory_rates_effective_from'), ['effective_from'], unique=True)

    op.create_table('wage_rate_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_company_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('pay_code', sa.String(length=20), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_company_id'], ['client_company.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_company_id', 'employee_id', 'pay_code', name='uq_wage_rate_scope_code')
    )
    with op.batch_alter_table('wage_rate_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wage_rate_profiles_client_company_id'), ['client_company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wage_rate_profiles_employee_id'), ['employee_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wage_rate_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wage_rate_profiles_employee_id'))
        batch_op.drop_index(batch_op.f('ix_wage_rate_profiles_client_company_id'))

    op.drop_table('wage_rate_profiles')
    with op.batch_alter_table('statutory_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_statutory_rates_effective_from'))

    op.drop_table('statutory_rates')
    # ### end Alembic commands ###
