"""real baseline: create the schema d450b1a3317e assumed already existed

The chain used to start at ``d450b1a3317e``, which adds four sets of foreign
keys and creates nothing. It was autogenerated against a database that
``db.create_all()`` had already built, so ``flask db upgrade`` on an empty
database failed on the very first revision with ``NoSuchTableError: expense``.
Every environment reached its schema through ``create_all()`` and layered the
migrations on top; none was ever built from the chain alone. That made the
migration history unable to rebuild the database it describes — a disaster
recovery gap on the web app, and a blocker for any packaged install whose first
run has nothing to layer onto.

This revision is that missing root. It creates the schema **as it stood when
d450b1a3317e was written** — not the schema of today:

  * 29 tables, being the models as of ``a9771c3^`` (the commit before the
    July-3 payroll-core refactor, which is where ``migrations/`` was born).
  * That deliberately includes the 14 archived operations tables — invoice,
    product, supplier, cleaning_job and the rest. ``f969702561b6`` drops them
    a few revisions later. Creating them here so a later revision can drop
    them looks redundant, and is: it is what makes the 32 revisions after this
    one apply to exactly the schema they were written against, which is the
    only way the chain reproduces the real database.
  * It does NOT create the seven foreign keys ``d450b1a3317e`` adds. The live
    database genuinely lacked them — that is why the baseline was generated to
    add them — so leaving them out keeps that revision meaningful and avoids
    double-adding the constraint on PostgreSQL.

Existing deployments are unaffected. Their ``alembic_version`` already names a
descendant of ``d450b1a3317e``, and Alembic only walks from the current
revision forward, so this root is never replayed against a database that has
one.

Revision ID: f0e1d2c3b4a5
Revises:
Create Date: 2026-08-14 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e1d2c3b4a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('contact_person', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('service_type', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('idempotency_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idempotency_key_key'), 'idempotency_key', ['key'], unique=True)
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('contact_person', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.String(length=60), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('ghana_card_number', sa.String(length=80), nullable=True),
    sa.Column('ssnit_number', sa.String(length=80), nullable=True),
    sa.Column('bank_name', sa.String(length=120), nullable=True),
    sa.Column('bank_account_number', sa.String(length=80), nullable=True),
    sa.Column('momo_number', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('employment_type', sa.String(length=80), nullable=True),
    sa.Column('service_line', sa.String(length=120), nullable=True),
    sa.Column('assigned_client', sa.String(length=160), nullable=True),
    sa.Column('client_company_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('preferred_channel', sa.String(length=16), nullable=True),
    sa.Column('department', sa.String(length=80), nullable=True),
    sa.Column('basic_salary', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_company_id'], ['client_company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_staff_id'), 'employee', ['staff_id'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=180), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('default_unit_price', sa.Float(), nullable=True),
    sa.Column('current_stock', sa.Float(), nullable=True),
    sa.Column('reorder_level', sa.Float(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('client_company_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('audit_trail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_role', sa.String(length=40), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('related_record_type', sa.String(length=80), nullable=True),
    sa.Column('related_record_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cleaning_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_company_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=180), nullable=False),
    sa.Column('job_type', sa.String(length=80), nullable=False),
    sa.Column('location', sa.String(length=180), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('checklist', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_company_id'], ['client_company.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cleaning_job_client_company_id'), 'cleaning_job', ['client_company_id'], unique=False)
    op.create_index(op.f('ix_cleaning_job_scheduled_date'), 'cleaning_job', ['scheduled_date'], unique=False)
    op.create_table('client_service_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_company_id', sa.Integer(), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('request_type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requested_date', sa.Date(), nullable=True),
    sa.Column('preferred_start_time', sa.Time(), nullable=True),
    sa.Column('preferred_end_time', sa.Time(), nullable=True),
    sa.Column('location', sa.String(length=180), nullable=True),
    sa.Column('number_of_workers_requested', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_company_id'], ['client_company.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_service_request_client_company_id'), 'client_service_request', ['client_company_id'], unique=False)
    op.create_table('employee_deployment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('client_company_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_company_id'], ['client_company.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_deployment_client_company_id'), 'employee_deployment', ['client_company_id'], unique=False)
    op.create_index(op.f('ix_employee_deployment_employee_id'), 'employee_deployment', ['employee_id'], unique=False)
    op.create_table('inventory_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('reference_type', sa.String(length=80), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movement_product_id'), 'inventory_movement', ['product_id'], unique=False)
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_company_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=80), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('billing_period_start', sa.Date(), nullable=True),
    sa.Column('billing_period_end', sa.Date(), nullable=True),
    sa.Column('invoice_type', sa.String(length=80), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('balance_due', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_company_id'], ['client_company.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index(op.f('ix_invoice_client_company_id'), 'invoice', ['client_company_id'], unique=False)
    op.create_table('payroll_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('client_company_id', sa.Integer(), nullable=True),
    sa.Column('total_workers', sa.Integer(), nullable=True),
    sa.Column('total_rows_imported', sa.Integer(), nullable=True),
    sa.Column('total_unique_workers', sa.Integer(), nullable=True),
    sa.Column('duplicate_workers_found', sa.Integer(), nullable=True),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('source_sheet_name', sa.String(length=160), nullable=True),
    sa.Column('detected_header_row', sa.Integer(), nullable=True),
    sa.Column('import_mode', sa.String(length=40), nullable=True),
    sa.Column('import_type', sa.String(length=80), nullable=True),
    sa.Column('detected_company_name', sa.String(length=160), nullable=True),
    sa.Column('active_workers', sa.Integer(), nullable=True),
    sa.Column('inactive_workers', sa.Integer(), nullable=True),
    sa.Column('terminated_workers', sa.Integer(), nullable=True),
    sa.Column('on_leave_workers', sa.Integer(), nullable=True),
    sa.Column('unknown_status_workers', sa.Integer(), nullable=True),
    sa.Column('total_gross_pay', sa.Float(), nullable=True),
    sa.Column('total_deductions', sa.Float(), nullable=True),
    sa.Column('total_net_pay', sa.Float(), nullable=True),
    sa.Column('total_paye', sa.Float(), nullable=True),
    sa.Column('total_ssnit', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('upload_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['client_company_id'], ['client_company.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_company_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('service_summary', sa.Text(), nullable=False),
    sa.Column('proposed_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('drafted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_company_id'], ['client_company.id'], ),
    sa.ForeignKeyConstraint(['drafted_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('client_company_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('site_location', sa.String(length=160), nullable=True),
    sa.Column('assignment_start_date', sa.Date(), nullable=False),
    sa.Column('assignment_end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('shift_type', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_company_id'], ['client_company.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_assignment_client_company_id'), 'worker_assignment', ['client_company_id'], unique=False)
    op.create_index(op.f('ix_worker_assignment_employee_id'), 'worker_assignment', ['employee_id'], unique=False)
    op.create_table('attendance_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('client_company_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('clock_in', sa.Time(), nullable=True),
    sa.Column('clock_out', sa.Time(), nullable=True),
    sa.Column('hours_worked', sa.Float(), nullable=True),
    sa.Column('overtime_hours', sa.Float(), nullable=True),
    sa.Column('attendance_status', sa.String(length=40), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['worker_assignment.id'], ),
    sa.ForeignKeyConstraint(['client_company_id'], ['client_company.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_record_client_company_id'), 'attendance_record', ['client_company_id'], unique=False)
    op.create_index(op.f('ix_attendance_record_employee_id'), 'attendance_record', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_record_work_date'), 'attendance_record', ['work_date'], unique=False)
    op.create_table('cleaning_job_worker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cleaning_job_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=60), nullable=False),
    sa.Column('attendance_status', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cleaning_job_id'], ['cleaning_job.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cleaning_job_worker_cleaning_job_id'), 'cleaning_job_worker', ['cleaning_job_id'], unique=False)
    op.create_index(op.f('ix_cleaning_job_worker_employee_id'), 'cleaning_job_worker', ['employee_id'], unique=False)
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('payment_method', sa.String(length=80), nullable=True),
    sa.Column('receipt_reference', sa.String(length=120), nullable=True),
    sa.Column('receipt_attachment', sa.String(length=255), nullable=True),
    sa.Column('paid_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('client_company_id', sa.Integer(), nullable=True),
    sa.Column('payroll_run_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recorded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goods_supply_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_company_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=80), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('requested_delivery_date', sa.Date(), nullable=True),
    sa.Column('delivery_location', sa.String(length=180), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('related_service_request_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_company_id'], ['client_company.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['related_service_request_id'], ['client_service_request.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_index(op.f('ix_goods_supply_order_client_company_id'), 'goods_supply_order', ['client_company_id'], unique=False)
    op.create_table('import_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_company_id', sa.Integer(), nullable=True),
    sa.Column('payroll_month', sa.String(length=20), nullable=False),
    sa.Column('payroll_year', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('import_mode', sa.String(length=40), nullable=True),
    sa.Column('source_sheet_name', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('valid_rows', sa.Integer(), nullable=True),
    sa.Column('invalid_rows', sa.Integer(), nullable=True),
    sa.Column('total_workers', sa.Integer(), nullable=True),
    sa.Column('gross_total', sa.Float(), nullable=True),
    sa.Column('net_total', sa.Float(), nullable=True),
    sa.Column('paye_total', sa.Float(), nullable=True),
    sa.Column('ssnit_total', sa.Float(), nullable=True),
    sa.Column('validation_summary', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('payroll_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_company_id'], ['client_company.id'], ),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_run.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('line_total', sa.Float(), nullable=True),
    sa.Column('source_type', sa.String(length=80), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_item_invoice_id'), 'invoice_item', ['invoice_id'], unique=False)
    op.create_table('invoice_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('payment_method', sa.String(length=40), nullable=True),
    sa.Column('reference_number', sa.String(length=120), nullable=True),
    sa.Column('received_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_payment_invoice_id'), 'invoice_payment', ['invoice_id'], unique=False)
    op.create_table('job_completion_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cleaning_job_id', sa.Integer(), nullable=False),
    sa.Column('completed_by', sa.Integer(), nullable=True),
    sa.Column('completion_status', sa.String(length=80), nullable=False),
    sa.Column('workers_present', sa.Integer(), nullable=True),
    sa.Column('workers_absent', sa.Integer(), nullable=True),
    sa.Column('checklist_completed', sa.Boolean(), nullable=True),
    sa.Column('issues_found', sa.Text(), nullable=True),
    sa.Column('client_feedback', sa.Text(), nullable=True),
    sa.Column('supervisor_comments', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cleaning_job_id'], ['cleaning_job.id'], ),
    sa.ForeignKeyConstraint(['completed_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cleaning_job_id')
    )
    op.create_table('payment_voucher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_run_id', sa.Integer(), nullable=True),
    sa.Column('voucher_number', sa.String(length=80), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('gross_payroll', sa.Float(), nullable=True),
    sa.Column('total_deductions', sa.Float(), nullable=True),
    sa.Column('net_amount_payable', sa.Float(), nullable=True),
    sa.Column('prepared_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('date_approved', sa.DateTime(), nullable=True),
    sa.Column('date_paid', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_run.id'], ),
    sa.ForeignKeyConstraint(['prepared_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voucher_number')
    )
    op.create_table('payroll_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_run_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('staff_id', sa.String(length=60), nullable=True),
    sa.Column('full_name', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('service_line', sa.String(length=120), nullable=True),
    sa.Column('job_role', sa.String(length=120), nullable=True),
    sa.Column('payroll_month', sa.String(length=40), nullable=True),
    sa.Column('ssnit_number', sa.String(length=80), nullable=True),
    sa.Column('ghana_card_number', sa.String(length=80), nullable=True),
    sa.Column('bank_name', sa.String(length=120), nullable=True),
    sa.Column('bank_account_number', sa.String(length=80), nullable=True),
    sa.Column('momo_number', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('basic_salary', sa.Float(), nullable=True),
    sa.Column('transport_allowance', sa.Float(), nullable=True),
    sa.Column('housing_allowance', sa.Float(), nullable=True),
    sa.Column('overtime_hours', sa.Float(), nullable=True),
    sa.Column('overtime_pay', sa.Float(), nullable=True),
    sa.Column('other_allowances', sa.Float(), nullable=True),
    sa.Column('gross_pay', sa.Float(), nullable=True),
    sa.Column('paye', sa.Float(), nullable=True),
    sa.Column('ssnit', sa.Float(), nullable=True),
    sa.Column('tier_2_pension', sa.Float(), nullable=True),
    sa.Column('loan_deduction', sa.Float(), nullable=True),
    sa.Column('other_deductions', sa.Float(), nullable=True),
    sa.Column('total_deductions', sa.Float(), nullable=True),
    sa.Column('net_pay', sa.Float(), nullable=True),
    sa.Column('validation_status', sa.String(length=40), nullable=True),
    sa.Column('warning_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_pay_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_run_id', sa.Integer(), nullable=False),
    sa.Column('employee_id_str', sa.String(length=20), nullable=False),
    sa.Column('pay_code', sa.String(length=20), nullable=False),
    sa.Column('hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remittance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_run_id', sa.Integer(), nullable=True),
    sa.Column('remittance_type', sa.String(length=20), nullable=False),
    sa.Column('amount_due', sa.Float(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('date_paid', sa.Date(), nullable=True),
    sa.Column('payment_reference', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goods_supply_order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goods_supply_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('line_total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['goods_supply_order_id'], ['goods_supply_order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_supply_order_item_goods_supply_order_id'), 'goods_supply_order_item', ['goods_supply_order_id'], unique=False)
    op.create_table('payslip_delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_item_id', sa.Integer(), nullable=False),
    sa.Column('payroll_run_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('recipient', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('error', sa.String(length=512), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payroll_item_id'], ['payroll_item.id'], ),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payslip_delivery_payroll_item_id'), 'payslip_delivery', ['payroll_item_id'], unique=False)
    op.create_index(op.f('ix_payslip_delivery_payroll_run_id'), 'payslip_delivery', ['payroll_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payslip_delivery_payroll_run_id'), table_name='payslip_delivery')
    op.drop_index(op.f('ix_payslip_delivery_payroll_item_id'), table_name='payslip_delivery')
    op.drop_table('payslip_delivery')
    op.drop_index(op.f('ix_goods_supply_order_item_goods_supply_order_id'), table_name='goods_supply_order_item')
    op.drop_table('goods_supply_order_item')
    op.drop_table('remittance')
    op.drop_table('raw_pay_entries')
    op.drop_table('payroll_item')
    op.drop_table('payment_voucher')
    op.drop_table('job_completion_report')
    op.drop_index(op.f('ix_invoice_payment_invoice_id'), table_name='invoice_payment')
    op.drop_table('invoice_payment')
    op.drop_index(op.f('ix_invoice_item_invoice_id'), table_name='invoice_item')
    op.drop_table('invoice_item')
    op.drop_table('import_batch')
    op.drop_index(op.f('ix_goods_supply_order_client_company_id'), table_name='goods_supply_order')
    op.drop_table('goods_supply_order')
    op.drop_table('expense')
    op.drop_index(op.f('ix_cleaning_job_worker_employee_id'), table_name='cleaning_job_worker')
    op.drop_index(op.f('ix_cleaning_job_worker_cleaning_job_id'), table_name='cleaning_job_worker')
    op.drop_table('cleaning_job_worker')
    op.drop_index(op.f('ix_attendance_record_work_date'), table_name='attendance_record')
    op.drop_index(op.f('ix_attendance_record_employee_id'), table_name='attendance_record')
    op.drop_index(op.f('ix_attendance_record_client_company_id'), table_name='attendance_record')
    op.drop_table('attendance_record')
    op.drop_index(op.f('ix_worker_assignment_employee_id'), table_name='worker_assignment')
    op.drop_index(op.f('ix_worker_assignment_client_company_id'), table_name='worker_assignment')
    op.drop_table('worker_assignment')
    op.drop_table('proposal')
    op.drop_table('payroll_run')
    op.drop_index(op.f('ix_invoice_client_company_id'), table_name='invoice')
    op.drop_table('invoice')
    op.drop_index(op.f('ix_inventory_movement_product_id'), table_name='inventory_movement')
    op.drop_table('inventory_movement')
    op.drop_index(op.f('ix_employee_deployment_employee_id'), table_name='employee_deployment')
    op.drop_index(op.f('ix_employee_deployment_client_company_id'), table_name='employee_deployment')
    op.drop_table('employee_deployment')
    op.drop_index(op.f('ix_client_service_request_client_company_id'), table_name='client_service_request')
    op.drop_table('client_service_request')
    op.drop_index(op.f('ix_cleaning_job_scheduled_date'), table_name='cleaning_job')
    op.drop_index(op.f('ix_cleaning_job_client_company_id'), table_name='cleaning_job')
    op.drop_table('cleaning_job')
    op.drop_table('audit_trail')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('product')
    op.drop_index(op.f('ix_employee_staff_id'), table_name='employee')
    op.drop_table('employee')
    op.drop_table('supplier')
    op.drop_index(op.f('ix_idempotency_key_key'), table_name='idempotency_key')
    op.drop_table('idempotency_key')
    op.drop_table('client_company')
    # ### end Alembic commands ###
