"""drop archived ops-system tables

Revision ID: f969702561b6
Revises: d450b1a3317e
Create Date: 2026-07-02 09:49:25.082709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f969702561b6'
down_revision = 'd450b1a3317e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_service_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_service_request_client_company_id'))

    op.drop_table('client_service_request')
    with op.batch_alter_table('cleaning_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cleaning_job_client_company_id'))
        batch_op.drop_index(batch_op.f('ix_cleaning_job_scheduled_date'))

    op.drop_table('cleaning_job')
    with op.batch_alter_table('goods_supply_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goods_supply_order_client_company_id'))

    op.drop_table('goods_supply_order')
    with op.batch_alter_table('worker_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_assignment_client_company_id'))
        batch_op.drop_index(batch_op.f('ix_worker_assignment_employee_id'))

    op.drop_table('worker_assignment')
    op.drop_table('product')
    with op.batch_alter_table('attendance_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_record_client_company_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_record_employee_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_record_work_date'))

    op.drop_table('attendance_record')
    with op.batch_alter_table('inventory_movement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_movement_product_id'))

    op.drop_table('inventory_movement')
    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_item_invoice_id'))

    op.drop_table('invoice_item')
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_client_company_id'))

    op.drop_table('invoice')
    with op.batch_alter_table('goods_supply_order_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goods_supply_order_item_goods_supply_order_id'))

    op.drop_table('goods_supply_order_item')
    with op.batch_alter_table('cleaning_job_worker', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cleaning_job_worker_cleaning_job_id'))
        batch_op.drop_index(batch_op.f('ix_cleaning_job_worker_employee_id'))

    op.drop_table('cleaning_job_worker')
    with op.batch_alter_table('invoice_payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_payment_invoice_id'))

    op.drop_table('invoice_payment')
    op.drop_table('job_completion_report')
    op.drop_table('supplier')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=160), nullable=False),
    sa.Column('contact_person', sa.VARCHAR(length=120), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=40), nullable=True),
    sa.Column('email', sa.VARCHAR(length=160), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=40), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_completion_report',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cleaning_job_id', sa.INTEGER(), nullable=False),
    sa.Column('completed_by', sa.INTEGER(), nullable=True),
    sa.Column('completion_status', sa.VARCHAR(length=80), nullable=False),
    sa.Column('workers_present', sa.INTEGER(), nullable=True),
    sa.Column('workers_absent', sa.INTEGER(), nullable=True),
    sa.Column('checklist_completed', sa.BOOLEAN(), nullable=True),
    sa.Column('issues_found', sa.TEXT(), nullable=True),
    sa.Column('client_feedback', sa.TEXT(), nullable=True),
    sa.Column('supervisor_comments', sa.TEXT(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['cleaning_job_id'], ['cleaning_job.id'], ),
    sa.ForeignKeyConstraint(['completed_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cleaning_job_id')
    )
    op.create_table('invoice_payment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), nullable=False),
    sa.Column('payment_date', sa.DATE(), nullable=False),
    sa.Column('amount_paid', sa.FLOAT(), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=40), nullable=True),
    sa.Column('reference_number', sa.VARCHAR(length=120), nullable=True),
    sa.Column('received_by', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_payment_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('cleaning_job_worker',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cleaning_job_id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=60), nullable=False),
    sa.Column('attendance_status', sa.VARCHAR(length=40), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['cleaning_job_id'], ['cleaning_job.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cleaning_job_worker', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cleaning_job_worker_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cleaning_job_worker_cleaning_job_id'), ['cleaning_job_id'], unique=False)

    op.create_table('goods_supply_order_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('goods_supply_order_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('unit_price', sa.FLOAT(), nullable=True),
    sa.Column('line_total', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['goods_supply_order_id'], ['goods_supply_order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goods_supply_order_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goods_supply_order_item_goods_supply_order_id'), ['goods_supply_order_id'], unique=False)

    op.create_table('invoice',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_company_id', sa.INTEGER(), nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(length=80), nullable=False),
    sa.Column('invoice_date', sa.DATE(), nullable=False),
    sa.Column('due_date', sa.DATE(), nullable=True),
    sa.Column('billing_period_start', sa.DATE(), nullable=True),
    sa.Column('billing_period_end', sa.DATE(), nullable=True),
    sa.Column('invoice_type', sa.VARCHAR(length=80), nullable=False),
    sa.Column('subtotal', sa.FLOAT(), nullable=True),
    sa.Column('tax_amount', sa.FLOAT(), nullable=True),
    sa.Column('discount_amount', sa.FLOAT(), nullable=True),
    sa.Column('total_amount', sa.FLOAT(), nullable=True),
    sa.Column('amount_paid', sa.FLOAT(), nullable=True),
    sa.Column('balance_due', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=40), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['client_company_id'], ['client_company.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_client_company_id'), ['client_company_id'], unique=False)

    op.create_table('invoice_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('unit_price', sa.FLOAT(), nullable=True),
    sa.Column('line_total', sa.FLOAT(), nullable=True),
    sa.Column('source_type', sa.VARCHAR(length=80), nullable=True),
    sa.Column('source_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_item_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('inventory_movement',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('movement_type', sa.VARCHAR(length=40), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('reference_type', sa.VARCHAR(length=80), nullable=True),
    sa.Column('reference_id', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_movement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_movement_product_id'), ['product_id'], unique=False)

    op.create_table('attendance_record',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('client_company_id', sa.INTEGER(), nullable=False),
    sa.Column('assignment_id', sa.INTEGER(), nullable=True),
    sa.Column('work_date', sa.DATE(), nullable=False),
    sa.Column('clock_in', sa.TIME(), nullable=True),
    sa.Column('clock_out', sa.TIME(), nullable=True),
    sa.Column('hours_worked', sa.FLOAT(), nullable=True),
    sa.Column('overtime_hours', sa.FLOAT(), nullable=True),
    sa.Column('attendance_status', sa.VARCHAR(length=40), nullable=False),
    sa.Column('remarks', sa.TEXT(), nullable=True),
    sa.Column('recorded_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['worker_assignment.id'], ),
    sa.ForeignKeyConstraint(['client_company_id'], ['client_company.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_record_work_date'), ['work_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_record_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_record_client_company_id'), ['client_company_id'], unique=False)

    op.create_table('product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=180), nullable=False),
    sa.Column('sku', sa.VARCHAR(length=80), nullable=False),
    sa.Column('category', sa.VARCHAR(length=80), nullable=True),
    sa.Column('unit', sa.VARCHAR(length=40), nullable=True),
    sa.Column('default_unit_price', sa.FLOAT(), nullable=True),
    sa.Column('current_stock', sa.FLOAT(), nullable=True),
    sa.Column('reorder_level', sa.FLOAT(), nullable=True),
    sa.Column('supplier_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=40), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('worker_assignment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('client_company_id', sa.INTEGER(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=120), nullable=False),
    sa.Column('site_location', sa.VARCHAR(length=160), nullable=True),
    sa.Column('assignment_start_date', sa.DATE(), nullable=False),
    sa.Column('assignment_end_date', sa.DATE(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=40), nullable=False),
    sa.Column('shift_type', sa.VARCHAR(length=40), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['client_company_id'], ['client_company.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('worker_assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worker_assignment_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_assignment_client_company_id'), ['client_company_id'], unique=False)

    op.create_table('goods_supply_order',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_company_id', sa.INTEGER(), nullable=False),
    sa.Column('order_number', sa.VARCHAR(length=80), nullable=False),
    sa.Column('order_date', sa.DATE(), nullable=False),
    sa.Column('requested_delivery_date', sa.DATE(), nullable=True),
    sa.Column('delivery_location', sa.VARCHAR(length=180), nullable=True),
    sa.Column('status', sa.VARCHAR(length=40), nullable=True),
    sa.Column('subtotal', sa.FLOAT(), nullable=True),
    sa.Column('tax_amount', sa.FLOAT(), nullable=True),
    sa.Column('total_amount', sa.FLOAT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('related_service_request_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['client_company_id'], ['client_company.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['related_service_request_id'], ['client_service_request.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    with op.batch_alter_table('goods_supply_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goods_supply_order_client_company_id'), ['client_company_id'], unique=False)

    op.create_table('cleaning_job',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_company_id', sa.INTEGER(), nullable=False),
    sa.Column('job_title', sa.VARCHAR(length=180), nullable=False),
    sa.Column('job_type', sa.VARCHAR(length=80), nullable=False),
    sa.Column('location', sa.VARCHAR(length=180), nullable=True),
    sa.Column('scheduled_date', sa.DATE(), nullable=False),
    sa.Column('start_time', sa.TIME(), nullable=True),
    sa.Column('end_time', sa.TIME(), nullable=True),
    sa.Column('supervisor_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=40), nullable=False),
    sa.Column('checklist', sa.TEXT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['client_company_id'], ['client_company.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cleaning_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cleaning_job_scheduled_date'), ['scheduled_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_cleaning_job_client_company_id'), ['client_company_id'], unique=False)

    op.create_table('client_service_request',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_company_id', sa.INTEGER(), nullable=False),
    sa.Column('submitted_by', sa.INTEGER(), nullable=True),
    sa.Column('request_type', sa.VARCHAR(length=80), nullable=False),
    sa.Column('title', sa.VARCHAR(length=180), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('requested_date', sa.DATE(), nullable=True),
    sa.Column('preferred_start_time', sa.TIME(), nullable=True),
    sa.Column('preferred_end_time', sa.TIME(), nullable=True),
    sa.Column('location', sa.VARCHAR(length=180), nullable=True),
    sa.Column('number_of_workers_requested', sa.INTEGER(), nullable=True),
    sa.Column('priority', sa.VARCHAR(length=40), nullable=True),
    sa.Column('status', sa.VARCHAR(length=40), nullable=True),
    sa.Column('internal_notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['client_company_id'], ['client_company.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_service_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_service_request_client_company_id'), ['client_company_id'], unique=False)

    # ### end Alembic commands ###
